### ISSUE TITLE
php-openid-client installed with composer doesn't contain service builders

### ISSUE THREAD

**Issue by killua-eu** [facile-it/php-openid-client#14]
Using composer require fetches a version that doesnt have service builders (testing out the example right now).
Needed to modify composer.json to fetch dev-master "facile-it/php-openid-client": "dev-master". Maybe a new package would help, so that the README is in sync with the current release?

**Comment by thomasvargiu** [comment]
[v0.2.0](https://github.com/facile-it/php-openid-client/releases/tag/0.2.0) is released
