### ISSUE TITLE
Package web-token/jwt-easy is abandoned, you should avoid using it. No replacement was suggested.

### ISSUE THREAD

**Issue by marcing** [facile-it/php-openid-client#22]
Dependency should be updated as jwt-easy was removed.

**Comment by Jean85** [comment]
This is an indirect issue, rooted in https://github.com/facile-it/php-jose-verifier/, and it was already handled in https://github.com/facile-it/php-jose-verifier/pull/7, see https://github.com/facile-it/php-jose-verifier/pull/7/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L44

Updating to [0.4.1](https://github.com/facile-it/php-jose-verifier/releases/tag/0.4.1) should fix it.

**Comment by marcing** [comment]
Thank you Alessandro!
