### ISSUE TITLE
Example from README.md does not work due to missing class

### ISSUE THREAD

**Issue by ip6li** [facile-it/php-openid-client#31]
offending line is $issuer = (new IssuerBuilder())->build('https://example.com/.well-known/openid-configuration');

```
PHP Fatal error:  Uncaught Error: Class "Facile\OpenIDClient\Issuer\IssuerBuilder" not found
```

**Comment by amrita-shrestha** [comment]
maybe you miss `require_once(__DIR__ . "/../vendor/autoload.php");` @ip6li

**Comment by thomasvargiu** [comment]
@ip6li Sorry for the late answer. Did you resolve it? The class should exists.
