### ISSUE TITLE
Replace abandoned packages

### ISSUE THREAD

**Issue by vixducis** [facile-it/php-openid-client#39]
The following packages were all marked as abandoned on packagist.org, while this library still relies on them.
web-token/jwt-checker
web-token/jwt-core
web-token/jwt-encryption
web-token/jwt-key-mgmt
web-token/jwt-signature
web-token/jwt-signature-algorithm-rs

The author has indicated that web-token/jwt-library is the replacement package for all of the above. It looks like this should be a drop-in replacement. 

Could we update the dependencies in order to use the new library?

**Comment by thomasvargiu** [comment]
Hi @vixducis. There is an open PR that we still need to check (https://github.com/facile-it/php-openid-client/pull/37). It will probably be a new major release.

**Comment by vixducis** [comment]
Awesome, hadn't noticed that. looking forward to the update.
