### ISSUE TITLE
Including code_challenge_method in the auth URL

### ISSUE THREAD

**Issue by platomedical** [facile-it/php-openid-client#41]
Thank you for the awesome library! 

I am trying to generate the Auth URL using the `AuthorizationServiceBuilder` - however, I am not able to identify how to include the `code_challenge_method`, `code_challenge` and `nonce`/`state` query parameters.

Any advise is greatly appreciated.

-----

My code:
```
$issuer = (new IssuerBuilder())->build('https://id.xxxxxxxxx.com/.well-known/openid-configuration');
$clientMetadata = ClientMetadata::fromArray([
    'client_id' => 'xxxxxxx',
    'token_endpoint_auth_method' => 'private_key_jwt',
    'response_types'=>['code'],
    'id_token_signed_response_alg'=>'ES256',
    'userinfo_encrypted_response_alg'=>'ECDH-ES+A256KW',
    'userinfo_encrypted_response_enc'=>'A256GCM',
    'userinfo_signed_response_alg'=>'ES256',
    'redirect_uris' => [
        'https://xxxxxxx/callback',
    ],
    'jwks'=>json_decode(file_get_contents("/privatekeys.json"),true),
]);
$client = (new ClientBuilder())->setIssuer($issuer)->setClientMetadata($clientMetadata)->build();
$authorizationService = (new AuthorizationServiceBuilder())->build();
$redirectAuthorizationUri = $authorizationService->getAuthorizationUri(
	$client, ['scope'=>'openid name sex'] );
```

**Comment by thomasvargiu** [comment]
The Proof Key for Code Exchange (PKCE) is for public clients. You shouldn't need it (I guess) using this library that it's for server-side auth.

Is there a specific need?

**Comment by Potherca** [comment]
> Are you sure you're implementing the right flow for your app?

I'm _fairly_ sure that I need to follow the Authorization Code Flow (with offline access), but I'm not 100%.

If I do not add PKCE, I get:

```
[
  'error' => 'invalid_request',
  'error_description' => 'Authorization Server policy requires PKCE to be used for this request',
  'state' => 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzY4NTM5NDEsImlzc3IiOiJodHRwczpcL1wvc29saWRjb21tdW5pdHkubmV0In0.TAfetiOhm5n-jGdGN1Lf9_PbRvyGpgLCXPAVqyeZXvM',
  'iss' => 'https://solidcommunity.net/'
]
```

I've done plenty of browser only OAuth/OIDC, specifically for [the Solid Protocol](https://solidproject.org/TR/). But this is the first time I'm doing it server-side. 😓

My implementation example is currently working, but I still have to do some cleanup before I can publish it/share it here.
